theme: jekyll-theme-minimal
#title: Symmetries & Signals
#description: EigenTalks by Santanu Pattanayak
#show_downloads: true
google_analytics:
markdown: kramdown
kramdown:
  math_engine: mathjax
header:
  overlay_image: false
plugins:
  - jekyll-seo-tag

